<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use PDO;

/**
 * Create SQL dumps of the application database without shell commands.
 *
 * Works on shared hosting where `exec()` / `proc_open` are disabled
 * (e.g. Hostinger) — the dump is produced purely through PDO. Supports
 * both SQLite (local) and MySQL/MariaDB (production).
 *
 * Backups are stored on the local disk under `backups/` — never on the
 * public disk.
 */
class DatabaseBackupService
{
    /** Directory (relative to the local disk root) where backups live. */
    public const DIRECTORY = 'backups';

    /** Keep at most this many backups; older ones are pruned. */
    public const KEEP = 14;

    public function create(string $label = 'backup'): array
    {
        $connection = DB::connection();
        $driver = $connection->getDriverName();
        $pdo = $connection->getPdo();

        $filename = $this->filename($label, $driver);
        $relative = self::DIRECTORY . '/' . $filename;

        $sql = $this->dump($pdo, $driver);

        Storage::disk('local')->put($relative, $sql);

        $this->prune();

        return [
            'filename' => $filename,
            'size' => strlen($sql),
            'driver' => $driver,
            'created_at' => now(),
        ];
    }

    /** @return array<int, array{filename: string, size: int, created_at: \Illuminate\Support\Carbon}> */
    public function list(): array
    {
        $files = collect(Storage::disk('local')->files(self::DIRECTORY))
            ->filter(fn (string $path) => str_ends_with($path, '.sql'))
            ->map(function (string $path) {
                $created = $this->timestampFromFilename(basename($path));

                return [
                    'filename' => basename($path),
                    'size' => Storage::disk('local')->size($path),
                    'created_at' => $created,
                ];
            })
            ->sortByDesc('created_at')
            ->values();

        return $files->all();
    }

    public function path(string $filename): string
    {
        return self::DIRECTORY . '/' . basename($filename);
    }

    public function exists(string $filename): bool
    {
        return Storage::disk('local')->exists($this->path($filename));
    }

    public function delete(string $filename): bool
    {
        return Storage::disk('local')->delete($this->path($filename));
    }

    /** Remove the oldest backups once the count exceeds KEEP. */
    private function prune(): void
    {
        $backups = $this->list();

        if (count($backups) <= self::KEEP) {
            return;
        }

        foreach (array_slice($backups, self::KEEP) as $old) {
            $this->delete($old['filename']);
        }
    }

    private function filename(string $label, string $driver): string
    {
        $stamp = now()->format('Y-m-d_His');
        $safeLabel = preg_replace('/[^A-Za-z0-9_-]/', '_', $label) ?: 'backup';

        return "{$safeLabel}_{$stamp}.{$driver}.sql";
    }

    private function timestampFromFilename(string $filename): \Illuminate\Support\Carbon
    {
        if (preg_match('/(\d{4}-\d{2}-\d{2}_\d{6})/', $filename, $m)) {
            try {
                return \Illuminate\Support\Carbon::createFromFormat('Y-m-d_His', $m[1]);
            } catch (\Throwable) {
                // fall through to file modification time
            }
        }

        $full = $this->path($filename);
        $mtime = Storage::disk('local')->lastModified($full);

        return \Illuminate\Support\Carbon::createFromTimestamp($mtime);
    }

    private function dump(PDO $pdo, string $driver): string
    {
        $lines = [];
        $lines[] = '-- DataPOS database backup';
        $lines[] = '-- Driver: ' . $driver;
        $lines[] = '-- Created at: ' . now()->toDateTimeString();
        $lines[] = '-- Generated by the application (no shell tools required)';
        $lines[] = '';

        // Foreign keys must be off during restore so tables can be recreated
        // in any order (MySQL/MariaDB only — SQLite ignores these pragmas).
        $lines[] = 'SET FOREIGN_KEY_CHECKS = 0;';
        $lines[] = '';

        $tables = $this->tables($pdo, $driver);

        foreach ($tables as $table) {
            $lines = array_merge($lines, $this->dumpTable($pdo, $driver, $table));
            $lines[] = '';
        }

        $lines[] = 'SET FOREIGN_KEY_CHECKS = 1;';

        return implode(PHP_EOL, $lines);
    }

    /** @return array<int, string> */
    private function tables(PDO $pdo, string $driver): array
    {
        if ($driver === 'sqlite') {
            $rows = $pdo->query("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name")->fetchAll(PDO::FETCH_COLUMN);

            return $rows;
        }

        // MySQL / MariaDB
        return $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
    }

    /** @return array<int, string> */
    private function dumpTable(PDO $pdo, string $driver, string $table): array
    {
        $lines = [];

        // Schema
        if ($driver === 'sqlite') {
            $stmt = $pdo->prepare("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?");
            $stmt->execute([$table]);
            $create = $stmt->fetchColumn();
            if ($create) {
                $lines[] = 'DROP TABLE IF EXISTS `' . $table . '`;';
                $lines[] = $create . ';';
            }
        } else {
            $stmt = $pdo->prepare('SHOW CREATE TABLE `' . $table . '`');
            $stmt->execute();
            $row = $stmt->fetch(PDO::FETCH_NUM);
            $create = $row[1] ?? '';
            $lines[] = 'DROP TABLE IF EXISTS `' . $table . '`;';
            $lines[] = $create . ';';
        }

        $lines[] = '';

        // Data
        $stmt = $pdo->query('SELECT * FROM `' . $table . '`');
        $columns = $this->columns($stmt, $driver);
        $rows = $stmt->fetchAll(PDO::FETCH_NUM);

        if ($rows === []) {
            return $lines;
        }

        $colList = implode(', ', array_map(fn ($c) => '`' . $c . '`', $columns));

        foreach ($rows as $row) {
            $values = array_map(fn ($value) => $this->sqlValue($pdo, $value, $driver), $row);
            $lines[] = 'INSERT INTO `' . $table . '` (' . $colList . ') VALUES (' . implode(', ', $values) . ');';
        }

        return $lines;
    }

    /** @return array<int, string> */
    private function columns(\PDOStatement $stmt, string $driver): array
    {
        $count = $stmt->columnCount();
        $columns = [];

        for ($i = 0; $i < $count; $i++) {
            $meta = $stmt->getColumnMeta($i);
            $columns[] = (string) ($meta['name'] ?? $i);
        }

        return $columns;
    }

    private function sqlValue(PDO $pdo, mixed $value, string $driver): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        // PDO::quote() handles driver-specific escaping (e.g. doubling single
        // quotes for SQLite, backslash escaping for MySQL) far better than a
        // naive addslashes() and also handles binary data.
        $quoted = $pdo->quote((string) $value);

        return $quoted === false ? "''" : $quoted;
    }
}
